services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: charliebrown
      POSTGRES_PASSWORD: CanIEatCheese
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$BASE_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "charliebrown"
      DB_PASSWORD: "CanIEatCheese"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "http://127.0.0.1:5003"

volumes:
 pgdata: